### PR TITLE
return from redirect_to; fix typo

### LINKED ISSUE #2684: orgs_controller#shibboleth_ds: redirect should return
Please complete the following fields as applicable:

**Expected behaviour:**

**Actual behaviour:**

Rails complains that rendering happens twice.

Reason: https://github.com/DMPRoadmap/roadmap/blob/master/app/controllers/orgs_controller.rb#L88

The `redirect` does not issue a return from the function `shibboleth_ds` and therefore
https://github.com/DMPRoadmap/roadmap/blob/master/app/controllers/orgs_controller.rb#L96 is executed also.

**Steps to reproduce:**

* checkout version 2.2.0
* login
* make sure there are no organisations with a shibboleth scheme identifier
* go to `/orgs/shibboleth`

### PR DESCRIPTION
**Pull request by nicolasfranck**
Fixes #2684

### CODE REVIEW

File: app/controllers/super_admin/themes_controller.rb [hunk 1]
```diff
@@ -51,7 +51,7 @@ def destroy
         redirect_to super_admin_themes_path, notice: msg
       else
         flash.now[:alert] = failure_message(@theme, _("delete"))
-        redner :edit
+        render :edit
```
Comment (briri) [inline app/controllers/super_admin/themes_controller.rb:54]: good catch

**Review by briri — APPROVED** [review]
this looks good. thanks @nicolasfranck
