### PR TITLE
Fixes iteration error on templates_controller

### LINKED ISSUE #1363: Customized version of funder template not being used
Please complete the following fields as applicable:

**Expected behaviour:** 
The user is given the customized version of the funder template (if one is available for the research org they select)

**Actual behaviour:**
The user is sometimes given the base funder templates.

**Steps to reproduce:**
This may be specific to the deployment and its Ruby/Rails versions.
- As an org admin, login and customize a funder template
- Publish your customization
- Create a new plan (select the customizing org as the research org and then select the funder)

### PR DESCRIPTION
**Pull request by briri**
Fixes #1363 

Opted to work with a separate array to hold the funder templates. We can explore more elegant solutions to this as we work on the template versioning rework.

### CODE REVIEW

File: app/controllers/org_admin/templates_controller.rb [hunk 1]
```diff
@@ -375,15 +375,18 @@ def template_options()
...
+            funder_templates.each do |tmplt|
               customization = Template.valid.find_by(published: true, org_id: org_id, customization_of: tmplt.dmptemplate_id)
               if customization.present? && tmplt.created_at < customization.created_at
-                templates.delete(tmplt)
                 templates << customization
+              else
+                templates << tmplt
               end
             end
           end
```
Comment (jollopre) [inline app/controllers/org_admin/templates_controller.rb]: An alternative solution would be using map which iterates over the elements of a list but 'preserves' the original list.
```
templates = Template.valid.publicly_visible.where(published: true, org_id: funder_id)
unless org_id.blank?
   templates = templates.map do |tmpt|
      customization = Template.valid.find_by(published: true, org_id: org_id, customization_of: tmplt.dmptemplate_id)
      if customization.present? && tmpl.created_at < customization.created_at
         customization
      else
         tmpl
      end
   end
end
```
but in any case the performance is hit because we are doing N queries. I believe we can sort this issue easier with the new template scope query methods
