### PR TITLE
fix accordion and plus/minus

### LINKED ISSUE #2558: Accordion plus signs do not change
- The accordion +/- signs do not change when the panel is expanded/collapsed. Doesn't seem to be a JS function for this anymore. Should be easy to add to the existing `app/javascript/src/utils/accordion.js`
- The 'expand all' and 'collapse all' links are not working.

### PR DESCRIPTION
**Pull request by raycarrick-ed**
Fixes #2558  .

Changes proposed in this PR:
- small changes to JS to fix accordion and plus/minus signs

### CODE REVIEW

**Comment by xsrust** [comment]
Looks like ESLint's complaining about the number of spaces used (althought as a separate issue, ESLint the action isn't failing, just the one that gates asset-compilation)

to make troubleshooting the linter issues locally easier, you can run 
`yarn run eslint './app/javascript/**/*.js'` or `rails webpacker:compile`

File: app/javascript/packs/application.js [hunk 1]
```diff
@@ -27,6 +27,7 @@ import '../src/utils/autoComplete';
 import '../src/utils/externalLink';
 import '../src/utils/outOfFocus';
 import '../src/utils/paginable';
+import '../src/utils/panelHeading';
```
Comment (briri) [inline app/javascript/packs/application.js:30]: good catch

**Comment by briri** [comment]
as @xsrust noted, looks like maybe the linter does not like the spacing/indentation. Feel free to merge yourself once that's been addressed
