### PR TITLE
Fix 'back' button on preview so that it goes to appropriate edit/show

### LINKED ISSUE #1477: Cannot preview template or customization
When I click the Preview button for a template or customization I get the error below

preview-customiz-error

### PR DESCRIPTION
**Pull request by briri**
Fixes #1477 .
- Added checks for `template.latest?` and `customization_of` when determining which back button to present to user
- Added redirect on phases_controller.edit to phases_controller.show if edit page is accessed but the template is a customization

### CODE REVIEW

File: app/controllers/org_admin/phases_controller.rb [hunk 1]
```diff
@@ -29,15 +29,20 @@ def edit
...
-      render('container',
-        locals: { 
-          partial_path: 'edit',
-          template: phase.template,
-          phase: phase,
-          sections: phase.sections.order(:number).select(:id, :title, :modifiable),
-          current_section: section.present? ? Section.find_by(id: section, phase_id: phase.id) : nil
-        })
+      # User cannot edit a phase if its a customization so redirect to show
+      if phase.template.customization_of.present?
```
Comment (jollopre) [inline app/controllers/org_admin/phases_controller.rb]: I think this is too generic. A customizable template might have phases that do not belong to the customization_of template and therefore we should offer the possibility to edit them, am I right?
