### PR TITLE
fixed issues with request feedback emails

### LINKED ISSUE #1230: Request feedback emails sent to wrong recipient (researcher/admin)
In the following scenario:
        Sherrygmail is the researcher who asked for feedback. and received the following email.
        Sherry H. Lake is the admin who "completed" the feedback (clicked the "complete" link).  

        Seems that the researcher (Sherrygmail), should have received a "completed" email message and not the one below, which should have gone to the admin (and did on the initial feedback request).

        -------------------

        Hello Sherrygmail Lake,

        Sherry H Lake has requested feedback on a plan "Teas of the World." To add comments, please visit the 'Plans' page under the Admin menu in DMPTool - Stg and open the plan.

        All the best 
        The DMPTool - Stg team

        You may change your notification preferences on your profile page. Please do not reply to this email. If you have any questions or need help, please contact us at or visit https://dmptool-stg.cdlib.org/contact-us

		
image

### PR DESCRIPTION
**Pull request by briri**
Fixes #1230, #1231, #1232 .

### CODE REVIEW

File: app/models/plan.rb [hunk 1]
```diff
@@ -218,7 +218,8 @@ def request_feedback(user)
 
         if self.save!
           # Send an email confirmation to the owners and co-owners
-          deliver_if(recipients: self.owner_and_coowners, key: 'users.feedback_requested') do |r|
+          owners = User.joins(:roles).where('roles.plan_id =? AND roles.access IN (?)', self.id, Role.access_values_for(:administrator))
```
Comment (jollopre) [inline app/models/plan.rb]: owner_and_coowners class method is still used after the change? If not, please remove it!
