### PR TITLE
Fix for #3443 - bar chart click function broken in usage dashboard

### LINKED ISSUE #3443: Usage dashboard - bar chart click function broken
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
v4.1.1

**Expected behaviour:**
If a user clicks on one of the bars in the chart graph representing 'No. of users joined during last year' or 'No. plans during last year', it should take them to the list of users/plans created in that month 

**Actual behaviour:**
The following error is thrown when you click on a bar in the abovementioned charts:
`Uncaught TypeError: chart.getElementAtEvent is not a function`

**Steps to reproduce:**
Note: this requires admin permissions
Admin menu > Usage
Click on 'Statistics on your Users'
Click on a bar in the chart titled 'No. of users joined during last year' or 'No. of plans during last year'

### PR DESCRIPTION
**Pull request by gjacob24**
Fixes #3443 

Changes proposed in this PR:
- `getElementAtEvent` replaced by `getElementsAtEventForMode`

### CODE REVIEW

File: app/javascript/src/usage/index.js [hunk 1]
```diff
@@ -42,11 +42,12 @@ $(() => {
     const usersData = JSON.parse($('#users_joined').val());
     if (isObject(usersData)) {
       const chart = createChart('#yearly_users', usersData, '', (event) => {
-        const segment = chart.getElementAtEvent(event)[0];
+        const points = chart.getElementsAtEventForMode(event, 'nearest', { intersect: true }, true);
+        const segment = points[0];
         if (!isUndefined(segment)) {
           const target = $('#users_click_target').val();
           /* eslint-disable no-underscore-dangle, no-restricted-globals */
```
Comment (aaronskiba) [inline app/javascript/src/usage/index.js:49]: The bar chart click function is now working. :) Given these code changes, I think `no-underscore-dangle,` can now be removed from `eslint-disable` throughout the file (can be double-checked by executing `yarn run eslint app/javascript/src/usage/index.js`).

Comment (gjacob24) [reply app/javascript/src/usage/index.js:49]: Thanks Aaron! I didn't know that. I'll create another commit to remove it now.

**Review by benjaminfaure — APPROVED** [review]

File: app/javascript/src/usage/index.js (hunk 1 above)
Comment (aaronskiba) [reply app/javascript/src/usage/index.js]: No problem, the fix looks good. :)

It might even be good to do a refactor here? There is a lot of duplication amidst the original code. I just threw it into ChatGPT and got the following suggestion. I didn't really test it though.

```javascript
// Function to create a chart and handle redirection on click
function createChartWithRedirect(chartElementId, dataElementId, targetElementId) {
  if (!isUndefined($(dataElementId).val())) {
    const data = JSON.parse($(dataElementId).val());
    if (isObject(data)) {
      const chart = createChart(chartElementId, data, '', (event) => {
        const points = chart.getElementsAtEventForMode(event, 'nearest', { intersect: true }, true);
        const segment = points[0];
        if (!isUndefined(segment)) {
          const target = $(targetElementId).val();
          /* eslint-disable no-restricted-globals */
          const label = chart.data.labels[segment.index];
          $(location).attr('href', `${target}?${labelToUrl(label)}`);
          /* eslint-enable no-restricted-globals */
        }
      });
    }
  }
}

// Create the Users joined chart
createChartWithRedirect('#yearly_users', '#users_joined', '#users_click_target');

// Create the Plans created chart
createChartWithRedirect('#yearly_plans', '#plans_created', '#plans_click_target');
```
